Updates to run iostat and sar -fixes for whitelist/blacklist for k8s endpoint -iostat and sar now supported

diff --git a/sysstat-stop b/sysstat-stop
--- a/sysstat-stop
+++ b/sysstat-stop
@@ -3,9 +3,13 @@ exec >sysstat-stop-stderrout.txt
 exec 2>&1
 
 echo "args: $@"
-echo "pwd: `/bin/pwd`"
 echo "hostname: `hostname`"
 
-while read pid; do
-    kill -s SIGTERM $pid
-done <sysstat-pids.txt
+if [ -e sysstat-pids.txt ]; then
+    while read pid; do
+        kill -s SIGTERM $pid
+    done <sysstat-pids.txt
+else
+    echo "Could not find sysstst-pids.txt"
+    exit 1
+fi
